version: "3.7"
services:
  resto:
    build: .
    container_name: restoran
    image: restoran:latest
    ports:
      - 8080:8080
    networks:
      - rest-network
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    image: mysql:latest
    networks:
      - rest-network
    environment:
      - MYSQL_ROOT_PASSWORD=lozinka
      - MYSQL_DATABASE=restoran
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
networks:
  rest-network:
    driver: bridge
volumes:
  mysql-data: